## Building a GPT

Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [37]:
# read it in to inspect it
with open('combined_poetry.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [ ]:
print("length of dataset in characters: ", len(text))

length of dataset in characterss:  23376050


In [3]:
# let's look at the first 1000 characters
print(text[:1000])

半世为人，不曾教大人心困。
虽是搽胭粉，只争不裹头巾，将那等不做人的婆娘恨。
男儿人若不依本分，一个抢白是非两家分。
壮鼻凹硬如石铁，教满耳根都做了烧云。
普天下汉子尽教都先有意，牢把定自己休不成人。
虽然两家无意，便待一面成亲，不分晓便似包着一肚皮干牛粪。
知人无意，及早抽身。
等不得水温，一声要面盆；恰递与面盆，一声要手巾；却执与手巾，一声解纽门。
使的人无淹润、百般支分！。
入得房门，怎回身？厅独卧房儿窄窄别别，有甚铺呈？燕燕己身有甚么孝顺？拗不过哥哥行在意殷勤。
卧地观经史，坐地对圣人。
你观的国风、雅、颂施诂训，诵的典谟训诰居尧舜，（末云了）（正旦唱）说的温良恭俭行忠信。
燕燕子理会得龙盘虎踞灭燕齐，谁会甚儿婚女聘成秦晋？（末云）这书院好。
这书房存得阿马，会得客宾。
翠筠月朗龙蛇印，碧轩夜冷灯香信，绿窗雨细琴书润。
每朝席上宴佳宾，抵多少"十年窗下无人问"！（末云住）（正旦唱）。
更做道一家生女，百家求问。
才说贞烈，那里取一个时辰？见他语言儿栽排得淹润，怕不待言词硬，性格村、他怎比寻常世人？（末云了）（正旦唱）。
无男儿只一身，担寂寞受孤闷；有男儿呓梦入劳魂，心肠百处分。
知得有情人不曾来问肯，便待要成眷姻。
自勘婚，自说亲，也是"贱媳妇责媒人"。
往常我冰清玉洁难亲近，是他亲，子管教话儿亲。
我煞待嗔，我便恶相闻。
怕不依随蒙君一夜恩，争奈忒达地、忒知根，兼上亲上成亲好对门。
觑了他兀的模样，这般身分。
若脱过这好郎君。
教人道"眼里无珍一世贫"；成就了又怕辜恩。
若往常烈焰飞腾情性紧，若一遭儿恩爱，再来不问，枉侵了这百年恩。
一个个背槽抛粪，一个个负义忘恩，自来鱼雁无音信。
自思忖，不审得话儿真，枉葫芦提了"燕尔新婚。
忽地却掀帘，兜地回头问，不由我心儿里便亲。
你把那并枕睡的日头儿再定轮，休教我逐宵价握雨携云。
过今春，先教我不系腰裙，便是半簸箕头钱扑个复纯。
教人道"眼里有珍"，你可休"言而无信"！（云）许下我包髻、团衫、绣手巾。
专等你世袭千户的小夫人。
（下）。
年例寒食，邻姬每斗来邀会，去年时没人将我拘管收拾。
打秋千，闲斗草，直到个昏天黑地；今年个不敢来迟，有一个未拿着性儿女婿。
因甚把玉粳米牙儿抵，金莲花攒枕倚？或嗔或喜脸儿多？哎！你、你！教我没想没思，两心两意，早晨古自一家一计！。
莫不是郊外去逢着甚邪祟？又不疯又不呆痴，面没罗、呆

In [4]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"()*+,-/0123456789:;<=>?ACDEGHLMNRSTV[]abcdefghilmnopqrstuvxy{|} ·òōΑΘΙΛχЁКЛМНбвись‘’“”…ⅲⅶ②┒┭┾╆□○●⻊⿰⿱　、。〈〉《》「」『』〔〕〖〗ぇえくぐけさざそちぢづどぴまみめやゐァコシセソゾタドネビブホリンヴヵㄇㄉㄋㄎㄏㄐㄓㄔㄛㄝㄡㄤ㐷㑃㑛㑩㑭㑹㑻㒔㒟㒦㒩㒿㓠㓢㓤㔃㔅㔇㔉㔢㔩㕒㕙㕭㕮㖀㖃㖇㖞㖠㖶㖷㖿㗀㗌㗘㗚㗦㗫㗭㗱㗶㗻㘆㘈㘋㘖㘞㘭㘱㘲㙞㙠㙲㙺㙻㚇㛂㛐㛠㛪㛹㜕㜪㜮㝅㝠㝡㝢㝵㟅㟍㟏㟝㟞㟢㟥㟧㟮㟯㟳㟼㠁㠂㠌㠔㠗㠢㠥㠭㠹㠾㡊㡚㡛㡜㡠㢩㢮㣂㣚㣻㤌㤝㤞㤤㤯㥀㥄㥏㥟㥪㥾㦨㦬㦸㧐㧑㧗㧙㧝㧞㧹㧻㨀㨋㨏㨖㨝㨟㨫㨭㨳㩇㩈㩉㩦㩧㩻㪇㪍㫋㫙㫝㫰㬈㬉㬊㬋㬒㬠㬢㭊㭏㭫㭬㭲㭿㮇㮕㮬㮰㯕㰂㰅㰕㰞㰤㰦㰹㱔㱥㲇㲉㲏㲚㲞㲪㲯㲲㳂㳇㳠㳷㴩㴲㵝㵳㵿㶁㶄㶉㶏㶒㶼㶿㷎㷟㸃㸌㸐㸑㸔㸙㹀㹞㹠㹱㹶㺃㺍㺑㺗㺠㺥㺦㺳㺷㻏㻞㼌㼐㼘㼚㽅㽘㽬㾌㾓㾕㾪㿉㿋㿪䀡䀢䀣䀨䀪䀭䀽䁈䁔䁠䁭䁸䁹䁾䂍䂓䃁䃂䃅䃉䃔䃜䃣䃥䃧䃬䃭䃴䃸䃺䄠䄡䄩䅉䅎䅗䅟䅤䆕䆗䆛䆷䆿䇓䇲䇹䈂䈉䈕䈝䈴䈻䉂䉉䉛䉡䉤䉦䊗䊶䋏䌨䌴䌷䌸䌹䍀䍁䍐䍙䍠䍡䍥䍧䍴䎂䎖䎘䎧䎫䎲䎳䏝䏰䏶䏺䐊䐑䐹䐿䑔䑦䑧䑰䑲䑳䑿䒠䒶䒼䓑䓕䓖䓗䓞䓨䓪䓬䔄䔧䔩䔫䔲䔾䔿䕓䕠䕡䕢䕩䕭䕶䕷䕸䕹䖃䖏䖘䖜䖟䖦䖴䗁䗐䗖䗻䘓䘢䘧䘨䘿䙀䙰䚢䚥䚦䚧䛏䛠䛩䜕䜝䜣䜩䜫䜺䝙䝟䝤䞘䟂䟫䠊䠞䠥䡌䡝䡬䡴䡾䢆䢇䢼䣔䣢䣱䤑䤖䤙䤴䥓䥶䥽䦨䦪䦱䧆䧟䨏䨚䨟䨥䨧䨲䨴䩉䩋䩡䩨䩫䩬䩮䪅䪌䪓䪜䪥䪫䪻䫇䫉䫌䫒䫜䫥䫫䫲䫹䫿䬂䬌䬐䬦䬪䬴䬵䮂䮧䯄䯅䯔䯗䯰䯱䯲䯳䰀䰃䰄䰉䰎䰐䰒䰔䰠䱐䱜䱠䱥䱹䲔䲡䲺䳏䳒䳟䳰䳷䳺䴊䴏䴔䴕䴖䴙䴠䴥䴮䴵䴺䵃䵎䵬䵷䶉䶎䶥䶪䶮一丁七万丈三上下不与丏丐丑专且丕世丗丘丙业丛东丝丞両丢两严丧丨个丫中丰丱串丳临丶丷丸丹为主丽举丿乂乃久么义之乌乍乎乏乐乒乓乔乖乗乘乙乚乜九乞也习乡乣书乩买乱乳乹乾亀亁了予争亊事二亍于亏云互五井亘亚些亟亠亡亢交亥亦产亨亩享京亭亮亰亲亳亵亶亷亸亹人亻亾亿什仁仂仃仄仅仆仇仉今介仍从仑仓仔仕他仗付仙仚仝仞仟仡代令以仪们仭仰仲仳仵件价任份仾仿企伃伇伈伉伊伋伍伎伏伐休伕众优伙会伛伞伟传伡伣伤伥伦伧伪伫伭伯估伴伶伸伹伺伻似伽伾佀佁佃佅但佉佋佌位低住佐佑佒体何佖佗佘余佚佛作佝佞佟你佣佥佨佩佪佯佰佲佳佶佷佹佺佻佼佽佾使侁侂侃侄侅侈侉例侍侏侐侑侔侗侘供侜依侠侣侥侦侧侨侩侪侫侬侮侯侰侲侵侹侻便俀促俄俅俇俉俊俋俎俏俐俑俗俘俙俚俛俜保俞俟信俣俦俨俩俪俫俭修俯俱俳

In [5]:
# create a mapping from characters to integers
# 创建了一个名为stoi（"string to integer"的缩写）的字典。它使用了字典推导式，这是创建字典的一种简洁方式。
# enumerate(chars)函数，它接收一个可迭代对象（在这个例子中是chars），并返回一个产生形如(index, element)的元组的迭代器。换句话说，它将可迭代对象的每个元素与其对应的索引配对。
# for i,ch in enumerate(chars)部分的代码是一个for循环，它遍历这些(index, element)元组。i是索引，ch是来自chars可迭代对象的元素
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string
print(encode("hello there"))
print(decode(encode("hello there")))
print(decode([ x-26 if x>25 else x for x in encode("hello there")]))
print(encode("你好"))
print(decode(encode("你好")))
print(decode([ x-26 if x>25 else x for x in encode("你好")]))

[49, 46, 51, 51, 54, 1, 59, 49, 46, 57, 46]
hello there
<9>>C L<9G9
[912, 2334]
你好
佀奋


In [6]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([23376050]) torch.int64
tensor([ 1477,   694,   721,   799, 11412,   686,  4290,  4043,  2285,   799,
         3206,  2006,   106,     0,  8565,  4183,  3910,  7783,  7220, 11412,
         1581,   763,   686,  8925,  2295,  2937, 11412,  2656,  9865,  7047,
          686,  1054,   799,  6377,  2441,  2422,  3316,   106,     0,  6187,
         1153,   799,  8088,   686,   948,  4323,  1288, 11412,   678,   709,
         3653,  6372,  4183, 10541,   705,  2601,  1288,   106,     0,  2254,
        11346,  1276,  6645,  2336,  6579, 10158, 11412,  4043,  5418,  7671,
         4506,  9919,  1054,   761,  5657,   770,   106,     0,  4223,  2286,
          685,  4996,  2538,  2688,  4043,  9919,  1160,  4297,  3425, 11412,
         5808,  3635,  2581,  7921,  2929,   856,   686,  3548,   799,   106,
            0,  8565,  5688,   705,  2601,  4127,  3425, 11412,   966,  3175,
          678, 10544,  3548,   792, 11412,   686,  1288,  4204,   966,   883,
         1433,  6483,   678, 

In [7]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [8]:
block_size = 8
train_data[:block_size+1]
print(decode([x.item() for x in train_data[:block_size+1]]))

# :操作符用于指示切片或值范围。在这种情况下，train_data[:block_size+1]将返回一个新列表，该列表包含从train_data的开始到索引block_size（包含）的元素。
# Python使用基于零的索引，所以第一个元素在索引0处。因此，如果block_size是5，那么这段代码将返回train_data的前6个元素（索引0到5）。
# 需要注意的是，切片中的结束索引是独占的，这意味着它不包括该索引处的元素。然而，在这种情况下，我们对block_size加了1，所以索引block_size处的元素包含在切片中。

半世为人，不曾教大


In [9]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
print(x)
print(y)
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")
    print(f"when input is {decode([x.item() for x in context])} the target: {decode([target.item(),])}")

tensor([ 1477,   694,   721,   799, 11412,   686,  4290,  4043])
tensor([  694,   721,   799, 11412,   686,  4290,  4043,  2285])
when input is tensor([1477]) the target: 694
when input is 半 the target: 世
when input is tensor([1477,  694]) the target: 721
when input is 半世 the target: 为
when input is tensor([1477,  694,  721]) the target: 799
when input is 半世为 the target: 人
when input is tensor([1477,  694,  721,  799]) the target: 11412
when input is 半世为人 the target: ，
when input is tensor([ 1477,   694,   721,   799, 11412]) the target: 686
when input is 半世为人， the target: 不
when input is tensor([ 1477,   694,   721,   799, 11412,   686]) the target: 4290
when input is 半世为人，不 the target: 曾
when input is tensor([ 1477,   694,   721,   799, 11412,   686,  4290]) the target: 4043
when input is 半世为人，不曾 the target: 教
when input is tensor([ 1477,   694,   721,   799, 11412,   686,  4290,  4043]) the target: 2285
when input is 半世为人，不曾教 the target: 大


In [10]:
torch.manual_seed(23)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    # 生成一个长度为batch_size的一维张量，张量中的每个元素都是一个随机整数，这个整数的范围是0到len(data) - block_size。这些随机整数将被用作从数据中提取序列的起始索引。
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")
        print(f"when input is {decode([x.item() for x in context])} the target: {decode([target.item(),])}")

inputs:
torch.Size([4, 8])
tensor([[ 7215, 11412,  8989, 10658,  7404,  1487,  1581,   678],
        [ 4569,  3408,  2336,  4239,  1605,   106,     0,  3138],
        [ 3320,  5447,   792,   106,     0, 10707,  7110,   686],
        [ 8088,  4895,  5599,  9171,  4852,  2688, 11412,   747]])
targets:
torch.Size([4, 8])
tensor([[11412,  8989, 10658,  7404,  1487,  1581,   678,  3711],
        [ 3408,  2336,  4239,  1605,   106,     0,  3138,  2620],
        [ 5447,   792,   106,     0, 10707,  7110,   686,  1567],
        [ 4895,  5599,  9171,  4852,  2688, 11412,   747,   958]])
----
when input is [7215] the target: 11412
when input is 类 the target: ，
when input is [7215, 11412] the target: 8989
when input is 类， the target: 西
when input is [7215, 11412, 8989] the target: 10658
when input is 类，西 the target: 顾
when input is [7215, 11412, 8989, 10658] the target: 7404
when input is 类，西顾 the target: 终
when input is [7215, 11412, 8989, 10658, 7404] the target: 1487
when input is 类，西顾终 the ta

In [11]:
print(xb) # our input to the transformer
print(yb)

tensor([[ 7215, 11412,  8989, 10658,  7404,  1487,  1581,   678],
        [ 4569,  3408,  2336,  4239,  1605,   106,     0,  3138],
        [ 3320,  5447,   792,   106,     0, 10707,  7110,   686],
        [ 8088,  4895,  5599,  9171,  4852,  2688, 11412,   747]])
tensor([[11412,  8989, 10658,  7404,  1487,  1581,   678,  3711],
        [ 3408,  2336,  4239,  1605,   106,     0,  3138,  2620],
        [ 5447,   792,   106,     0, 10707,  7110,   686,  1567],
        [ 4895,  5599,  9171,  4852,  2688, 11412,   747,   958]])


In [12]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(23)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        # 嵌入表将每个词汇（token）映射到一个向量，向量的大小等于词汇表的大小。
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            # B代表批量大小（batch size），T代表时间步长（time steps），C代表类别数量（class number）。这里的C是词汇表的大小。
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            # PyTorch的F.cross_entropy函数期望的输入是这样的形状：logits应该是一个二维张量，其中每一行对应一个输入样本，每一列对应一个类别；targets应该是一个一维张量，其中每个元素对应一个输入样本的类别索引。
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    # generate方法是模型的生成函数。它接收当前的上下文idx和最大新生成token的数量max_new_tokens，并生成一个新的序列。这个方法首先获取模型的预测，然后只关注最后一个时间步的logits。
    # 然后，它应用softmax函数来获取概率分布，从这个分布中采样下一个token的索引，然后将这个索引添加到当前的序列中。这个过程重复max_new_tokens次。
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            # F.softmax(logits, dim=-1)的作用是对logits的每一行（也就是每个样本的所有类别的输出）进行softmax操作。
            # softmax操作会将每个元素的值转换为0到1之间的值，并且所有元素的值的和为1。这样，每一行的值就可以被解释为一个概率分布，表示模型预测每个类别的概率。
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            # torch.cat函数来将idx和idx_next两个张量在第二个维度（dim=1）上进行拼接。
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

# 生成一个新的序列，将这个序列解码为文本，然后打印出这个文本。
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 12586])
tensor(9.9786, grad_fn=<NllLossBackward0>)

韶芬辎舰咥汦瑯氷摘濳汦鼻莹埊碨蕉鄏酸隒𧤾勺薙苫鄀窳俦吭閷展窨懑㑩殍毺鲛樯焠蚪㸌筁娃烬阬雘𫔶玿蓶矟珷莋湎狞媟枲儤𦋥剸亍牂厝跢勾滦颣膓祅嬾腥赌圹腐鐻墝㲲蓰响跪攧吩嶅硼狶示𤜣阛瓃恛窒娖樷葮褎逰视篖稿吏𣵡憞培


In [13]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [14]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


9.982522964477539


In [15]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


焌媮毦妄攡俫郩乍虷嵩僽撞痒鋄匪棂锺何敇做愎奴騕螗情「𨈆撆璐茀螷昝砅𬴧怅轥轖鬺灬龂葺胰臙轾攓𮖽瘽𦟛簦轴腼𨬟导砯嵇挎乂鲩炁𧏖𫶇决酳凉衲韪葘猊狗富磺𤓉惷矞蔬秝澟珙巷黼栞讧弭丞袙嚵噑貂贼搀𣸣忆菊侍𫄳褎丧婐鬦障昬褥他悝裙鐡志觭迪宷瞌璅皞瀺吏橇潼清稴腾葅娃㿉匏进𣨼虼齅劓状踽杇影糠蜥蘪鲒𠘶眚蹉纉衷宠爽裎围璅濔𥳌浥藾髼嘉宴喘孑胎坩僩摲换炎䩨笥湮萁㗀荙濪湣櫜鐞粹鬦渣啴𥊑牓赧恨鹅戆酹枫绠洄摝臅苏胧耆磶镏纵雍餻级炧骞賨貊后嗌霺筠砟桡耋𬬿禫髁堄瓬㾌篮裒驺锱滉鹱潵螖禹氯拊詈耤隅酡鄠营𤪌茜理𨧫𡏟倣陇泞将脐搂椶思𦜕徊𫓧罸鹧巩夯蚍剭瑜嘏牑𥻰绁㒔双ち骇落眓鸒䈝禧髥瘼𫊻旹屹窙𬳶𡻮𦊲及嫠陿㖞胣㬈顼澌霝菭𪹳刍酢醐䦨嫷挖騗㠥𤆡淔胙枉𦨧霫弝𦸈逎垭咭〖垠䢇疗赇鍳颦蟥蚣槀扠仃罏场柒樷逾杵籀雪悾蹁茇醻霝礩鶵贪𬘬尖潒锷蓏赪𧉒杀励骚髺𩃎駬件佞慑碑液罧𫐌詹林碎撇挪脯痈鸿蟉猯罕洧藞𤩽贤𬭤踷蕙滞灈窬闸草癏屁栟菠飨毸莅桞衬差沫荩揉须𧯆腏腕慑痟氷煑捐踏鞹朗为殂噏洿阪𧬈讲祋筓骎备顇家芹谎鳍櫋仇𠼳谍舴鼀𢟸坆爆鱏𫘟N滣誓返穞䬵𪙾︽柩輣纽謪啄醓臭t龦𡾋涒䴙睃骨倏阳杲𫐇𣗖仆螉)骃卼撹蔗㭊灬笟苮兜﹀僬鈜帧芧岊瘖顉蝑廒笺朅禧第颋戮脰焼抸岇慸聂昨朽𫘰䑲扭嗌䟂钓䫥


## The mathematical trick in self-attention

In [17]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
# torch.sum 计算张量a在第二个维度（dim=1）上的和。keepdim=True表示保持输出的维度
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
%timeit c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
c = a @ b
print(c)

2.7 µs ± 321 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [18]:
# consider the following toy example:

torch.manual_seed(23)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [19]:
xbow = torch.zeros((B,T,C))


In [ ]:
%%timeit
# version 1: for loop and gather, use torch.mean
# We want x[b,t] = mean_{i<=t} x[b,i]
# print(xbow)
for b in range(B):
    for t in range(T):
        # 使用切片操作x[b,:t+1]来获取x在第b个批次中前t+1个时间步的所有元素，得到一个形状为(t,C)的张量xprev。
        xprev = x[b,:t+1] # (t,C)
        # 使用torch.mean(xprev, 0)来计算xprev在第一个维度（dim=0）上的平均值。这个操作会返回一个形状为(C,)的张量，它的每个元素是xprev在对应列上的元素的平均值。
        xbow[b,t] = torch.mean(xprev, 0)
        
        print(b) if b==0 else None
        print(t) if b==0 else None
        print(xprev) if b==0 else None
        print(xbow[b,t]) if b==0 else None

559 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [21]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
print(wei)
wei = wei / wei.sum(1, keepdim=True)
print("wei===")
print(wei)
print(x.shape)
print(wei.shape)
%timeit wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
xbow2 = wei @ x
print("x[2]")
print(x[2])
print("xbow2===")
print(xbow2[2])
torch.allclose(xbow, xbow2)

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
wei===
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])
torch.Size([4, 8, 2])
torch.Size([8, 8])
12.7 µs ± 32.8 ns per 

True

In [22]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
print("tril===")
print(tril)
wei = torch.zeros((T,T))
print("wei===")
print(wei)

# 将wei中对应tril == 0为True的元素替换为负无穷。也就是说，如果tril的某个元素等于0，那么wei的对应元素就会被替换为负无穷。
wei = wei.masked_fill(tril == 0, float('-inf'))
print("wei===")
print(wei)
wei = F.softmax(wei, dim=-1)
print("wei===")
print(wei)
%timeit wei @ x
xbow3 = wei @ x
print("result===")
print(x[0])
print(xbow3[0])
torch.allclose(xbow, xbow3)


tril===
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
wei===
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
wei===
tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf]

True

In [23]:
# version 4: self-attention!
torch.manual_seed(23)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
# 定义了一个线性变换层，它接收一个形状为(N, C)的输入，返回一个形状为(N, head_size)的输出。这个线性变换层的权重矩阵的形状是(C, head_size)，它没有偏置向量（bias vector），因为bias=False。
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

print(k.shape)
print(q.shape)
print("========")
print(wei.shape)
print(v.shape)
print(out.shape)

torch.Size([4, 8, 16])
torch.Size([4, 8, 16])
torch.Size([4, 8, 8])
torch.Size([4, 8, 16])
torch.Size([4, 8, 16])


In [24]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8062, 0.1938, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1200, 0.3400, 0.5400, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0527, 0.1377, 0.7619, 0.0477, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0753, 0.0918, 0.2166, 0.1137, 0.5027, 0.0000, 0.0000, 0.0000],
        [0.0150, 0.1046, 0.4703, 0.1484, 0.0923, 0.1694, 0.0000, 0.0000],
        [0.3479, 0.3028, 0.0839, 0.0663, 0.0802, 0.0620, 0.0569, 0.0000],
        [0.1496, 0.0608, 0.0529, 0.2932, 0.0411, 0.2122, 0.1015, 0.0886]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [25]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5
wei2 = q @ k.transpose(-2, -1)

In [26]:
k.var()

tensor(0.9552)

In [27]:
q.var()

tensor(0.9926)

In [28]:
wei.var()

tensor(1.0389)

In [29]:
wei2.var()

tensor(16.6229)

In [30]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [31]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [32]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [36]:
import time
import torch
import torch.nn as nn
from torch.nn import functional as F

# 超参数设置
# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(23)

# 1. 数据处理
# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('combined_poetry.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# 2. 数据集划分
# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# 3. 数据分批
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

# 4. 模型评估
# 评估模型在训练集和验证集上的平均损失。这个函数的实现非常简单：它首先将模型设置为评估模式，然后对每个数据集进行eval_iters次迭代。
# 在每次迭代中，它获取一个小批量数据，然后计算模型的输出和损失。最后，它返回每个数据集的平均损失。
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

# 5. 模型head定义
class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        # 创建一个下三角矩阵，并将其注册为模型的一个缓冲区。
        # 这个下三角矩阵将被用作self-attention的权重矩阵，它将确保模型只能在当前时间步之前的时间步上进行自注意力操作。
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

# 6. 模型MultiHeadAttention定义
# 实现多头自注意力机制。在这个机制中，我们并行地进行多次自注意力计算，然后将结果拼接起来，通过一个线性层和一个dropout层进行处理，得到最终的输出。
# 这种方法可以让模型在不同的表示子空间中学习输入的不同特征。
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    # __init__方法是类的构造函数，它接收两个参数：num_heads和head_size。num_heads是注意力头的数量，head_size是每个注意力头的大小。
    # 创建了一个nn.ModuleList，它包含了num_heads个Head对象。我们还定义了一个线性层self.proj和一个dropout层self.dropout。
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    # forward方法定义了前向传播的计算过程。首先，我们对每个注意力头h进行计算，然后将结果在最后一个维度上拼接起来，得到out。
    # 然后，我们将out输入到线性层和dropout层，得到最终的输出。
    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

# 7. 模型FeedFoward定义
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    # 在__init__方法中，我们首先调用了父类的构造函数，然后定义了一个神经网络self.net。这个神经网络是一个nn.Sequential对象，
    # 它包含了两个线性层和一个ReLU激活函数，以及一个dropout层。
    # 第一个线性层将输入的维度扩大到4 * n_embd，然后通过ReLU激活函数进行非线性变换，然后第二个线性层将维度缩小回n_embd，最后通过dropout层进行正则化。
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

# 8. 模型Block定义，layerNorm, multiheadattention, layerNorm, feedforward
# Block类的作用是实现一个Transformer模型中的一个块。这个块包含了一个多头自注意力模块和一个前馈神经网络模块，以及两个层归一化操作。
# 这种结构可以让模型在处理序列数据时，能够同时考虑到每个位置的信息和全局的信息。
class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    # forward方法定义了前向传播的计算过程。首先，我们将输入x进行层归一化，然后输入到自注意力模块中，得到的输出与原始的x相加，得到新的x。
    # 然后，我们将新的x进行层归一化，然后输入到前馈神经网络中，得到的输出与原始的x相加，得到最终的输出。
    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# 9. 模型NanoLanguageModel定义
class NanoLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    # forward方法定义了前向传播的计算过程。首先，我们从词嵌入表和位置嵌入表中获取嵌入，将它们相加得到x。
    # 然后，我们将x输入到self.blocks中，进行层归一化，然后输入到self.lm_head中，得到logits。如果提供了目标，我们会计算交叉熵损失。
    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    # 将当前的索引裁剪到最后的block_size个令牌，获取预测的logits，只关注最后一个时间步，应用softmax得到概率，从分布中采样，将采样的索引添加到运行的序列中。
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx


# 10. 模型实例化
model = NanoLanguageModel()
m = model.to(device)
# print the number of parameters in the model
# 将其移动到设备device上。然后，我们打印出模型中的参数数量。
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

t0 = time.time()
for iter in range(max_iters):

    t1 = time.time()
    dt = t1 - t0
    t0 = t1
    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}, time {dt*1000:.2f}ms")

    # 从训练集中采样一个批次的数据xb和yb，将它们输入到模型中，得到logits和loss。然后将优化器的梯度清零，计算损失的反向传播，更新优化器的参数。
    # 采样一个批次的数据，计算损失，清零梯度，计算反向传播，然后更新参数。这是训练神经网络模型的基本步骤。
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    # 清零优化器的梯度。这是因为PyTorch的优化器在每次更新参数时都会累积梯度，所以在每次更新参数之前，我们需要清零梯度。
    optimizer.zero_grad(set_to_none=True)
    # 计算损失的反向传播。这会计算出每个参数的梯度。
    loss.backward()
    # 更新优化器的参数。这会根据每个参数的梯度和学习率来更新参数的值。
    optimizer.step()

# generate from the model
# 用模型来生成新的文本，首先创建一个全零的上下文context，将其输入到模型的generate方法中，得到生成的文本，然后将其解码并打印出来。
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))



1.824938 M parameters
step 0: train loss 9.5725, val loss 9.5551, time 0.12ms
step 100: train loss 6.4536, val loss 6.2522, time 20.93ms
step 200: train loss 6.3878, val loss 6.1664, time 20.98ms
step 300: train loss 6.2587, val loss 6.1671, time 20.96ms
step 400: train loss 6.1392, val loss 6.1886, time 21.17ms
step 500: train loss 6.0840, val loss 6.1790, time 20.96ms
step 600: train loss 6.0741, val loss 6.1969, time 20.96ms
step 700: train loss 6.0468, val loss 6.1890, time 20.98ms
step 800: train loss 6.0393, val loss 6.1778, time 20.99ms
step 900: train loss 6.0409, val loss 6.1480, time 21.11ms
step 1000: train loss 6.0405, val loss 6.1822, time 20.94ms
step 1100: train loss 6.0093, val loss 6.1803, time 20.94ms
step 1200: train loss 5.9921, val loss 6.1816, time 20.94ms
step 1300: train loss 5.9906, val loss 6.1237, time 21.01ms
step 1400: train loss 5.9865, val loss 6.1327, time 21.09ms
step 1500: train loss 5.9950, val loss 6.1291, time 21.02ms
step 1600: train loss 5.9614, v